# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: cc-credit
    volumes:
      - ./initscript:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "38080:8080"
